// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3HK1CTmNbRGqpeA40jutJWQqlVirN7zE',
    appId: '1:135460265564:web:8f73897a60e8537fa71099',
    messagingSenderId: '135460265564',
    projectId: 'sme-project-desktop',
    authDomain: 'sme-project-desktop.firebaseapp.com',
    storageBucket: 'sme-project-desktop.firebasestorage.app',
    measurementId: 'G-0JWCFLL1S7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhDboIPK2BrkJa9eENiv8AMb1YvpBdLfA',
    appId: '1:135460265564:android:81fda3ea1b89925ca71099',
    messagingSenderId: '135460265564',
    projectId: 'sme-project-desktop',
    storageBucket: 'sme-project-desktop.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3wK4wluakEsaYNM7Ln4ndUsCbLj9gkbY',
    appId: '1:135460265564:ios:b57c29d6cf103f4aa71099',
    messagingSenderId: '135460265564',
    projectId: 'sme-project-desktop',
    storageBucket: 'sme-project-desktop.firebasestorage.app',
    iosBundleId: 'com.example.smeProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3wK4wluakEsaYNM7Ln4ndUsCbLj9gkbY',
    appId: '1:135460265564:ios:b57c29d6cf103f4aa71099',
    messagingSenderId: '135460265564',
    projectId: 'sme-project-desktop',
    storageBucket: 'sme-project-desktop.firebasestorage.app',
    iosBundleId: 'com.example.smeProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3HK1CTmNbRGqpeA40jutJWQqlVirN7zE',
    appId: '1:135460265564:web:38c60b1f3a0e6848a71099',
    messagingSenderId: '135460265564',
    projectId: 'sme-project-desktop',
    authDomain: 'sme-project-desktop.firebaseapp.com',
    storageBucket: 'sme-project-desktop.firebasestorage.app',
    measurementId: 'G-Q6M3CPFPE1',
  );

}